const express = require('express');
const axios = require('axios');
const app = express();

const MAX_MOVIE_SIZE_GB = 4;
const MAX_SERIES_SIZE_GB = 1.5;
const PER_SOURCE_LIMIT = 3;
const MIN_SEEDERS = 2;

const QUALITY_ORDER = ['1080p','720p','576p','480p','360p','240p','1080','720','480','360','webdl','webrip','bluray'];
const EXCLUDE_KEYWORDS = ['4k','2160p','screenr','screener','cam','3d'];
const PRIORITY_PROVIDERS = ['yts','eztv','nyasi'];
const BLOCKED_PROVIDERS = ['1337x','kickasstorrents','torrentgalaxy','magnetdl','horriblesubs','tokyotosho','anidex','rutor','rutracker','comando','bludv','micoleaodublado','torrent9','ilcorsaronero','mejortorrent','wolfmax4k','cinecalidad','besttorrents'];
const SUBTITLES_URL = 'https://opensubtitlesv3-pro.dexter21767.com/eyJsYW5ncyI6WyJhcmFiaWMiLCJlbmdsaXNoIl0sInNvdXJjZSI6InRydXN0ZWQiLCJhaVRyYW5zbGF0ZWQiOmZhbHNlLCJhdXRvQWRqdXN0bWVudCI6ZmFsc2V9';

function extractQuality(t){const m=t.match(/\b(\d{3,4}p)\b/i);if(m)return m[1].toLowerCase();const l=t.toLowerCase();return QUALITY_ORDER.find(q=>l.includes(q))||'other'}
function qualitySortKey(q){const i=QUALITY_ORDER.indexOf(q);return i>=0?i:QUALITY_ORDER.length}
function detectProvider(t){const m=t.match(/\[([^\]]+)\]/);return m?m[1].toLowerCase():'other'}
function providerSortKey(p){const i=PRIORITY_PROVIDERS.indexOf(p);return i>=0?i:PRIORITY_PROVIDERS.length}
function parseSizeGB(t){if(!t)return null;const m=t.match(/(?:💾|📦|Size:|size:)\s*([\d.]+)\s*(GB|MB|TB)/i);if(!m)return null;const v=parseFloat(m[1]),u=m[2].toUpperCase();if(u==='TB')return v*1024;if(u==='GB')return v;if(u==='MB')return v/1024;return null}
function parseSizeBytes(t){if(!t)return null;const m=t.match(/(?:💾|📦|Size:|size:)\s*([\d.]+)\s*(GB|MB|TB)/i);if(!m)return null;const v=parseFloat(m[1]),u=m[2].toUpperCase();if(u==='TB')return v*1024*1024*1024*1024;if(u==='GB')return v*1024*1024*1024;if(u==='MB')return v*1024*1024;return null}
function isProviderBlocked(t){const p=detectProvider(t);if(BLOCKED_PROVIDERS.includes(p))return true;const l=t.toLowerCase();return BLOCKED_PROVIDERS.some(b=>l.includes(b))}
function formatBytes(b){if(!b)return'';const g=b/(1024*1024*1024);if(g>=1)return g.toFixed(1)+' GB';const m=b/(1024*1024);return m.toFixed(0)+' MB'}
function getSeeders(t){const sm=t.match(/👤\s*(\d+)/);return sm?parseInt(sm[1]):0}
function extractMovieName(t){const fl=t.split('\n')[0].trim();const st=/[\s.]+(?:1080p|720p|480p|2160p|1440p|4K|WEBRip|WebDL|BluRay|BRRip|HDRip|HDTV|DVDRip|AMZN|WEB-DL|x265|x264|HEVC|AAC|AC3|EAC3|DDP|DDP5|5\.1|2\.0|H264|10bit|S\d{2}|COMPLETE|LiNE|Rapta|YTS|YIFY|RARBG|ETRG|EVO|GalaxyRG|Tigole|UTR|RMTeam|ION10|MeGusta|Vyndros|FLUX|TiPEX|eztv|EZTV)\b/i;const parts=fl.split(st);let name=parts[0].replace(/\./g,' ').replace(/\s+/g,' ').trim();name=name.replace(/\s+\b(19|20)\d{2}\b$/,'').trim();return name||'Unknown'}
function extractYear(t){const fl=t.split('\n')[0].trim();const ym=fl.match(/\b(19\d{2}|20\d{2})\b/);return ym?ym[1]:''}
function parseStreamInfo(s){const t=s.title||s.name||'';let resolution=null;const rm=t.match(/(2160p|1440p|1080p|720p|480p|360p)/i);if(rm)resolution=rm[1];let ripType='';const rp=['webdl','web-dl','webrip','web-rip','bluray','blu-ray','brrip','bdrip','hdrip','hdtv','dvdrip','dvdscr','hdcam','ts','tc','cam'];const lt=t.toLowerCase();for(const p of rp){if(lt.includes(p)){switch(p){case'webdl':case'web-dl':ripType='WebDL';break;case'webrip':case'web-rip':ripType='WEBRip';break;case'bluray':case'blu-ray':ripType='BluRay';break;case'brrip':case'bdrip':ripType='BRRip';break;case'hdrip':ripType='HDRip';break;case'hdtv':ripType='HDTV';break;case'dvdrip':ripType='DVDRip';break;default:ripType=p.toUpperCase()}break}}let seeders=getSeeders(t);let indexer=detectProvider(t);if(indexer==='other'){const im=t.match(/⚙️\s*(\S+)/);if(im)indexer=im[1];else if(s._source)indexer=s._source}const sizeBytes=parseSizeBytes(t);let languages=[];if(s.languages&&s.languages.length){languages=s.languages}else{const lm=t.match(/🇬🇧\s*([\s\S]+?)(?:\n|$)/);if(lm)languages=lm[1].split('•').map(l=>l.trim())}let audioInfo='';if(s.audioTags&&s.audioTags.length){audioInfo=s.audioTags.join(' • ')}else{const am=t.match(/(?:DDP|EAC3|AAC|AC3|MP3|FLAC|DTS|TrueHD)\s*\d?\.?\d?/gi);if(am)audioInfo=am.join(' • ')}return{resolution,ripType,seeders,indexer,sizeBytes,languages,audioInfo}}
function buildUnifiedTitle(s){const i=parseStreamInfo(s);const ot=s.title||s.name||'';const mn=extractMovieName(ot);const yr=extractYear(ot);const dn=yr?`${mn} (${yr})`:mn;const l1='🔆 '+dn;const l2='🙋🏻‍♂️ '+(i.seeders||'0');let l3='';if(i.sizeBytes)l3='💾 '+formatBytes(i.sizeBytes);const di=i.indexer&&i.indexer!=='other'?i.indexer.charAt(0).toUpperCase()+i.indexer.slice(1):'Unknown';const l4='🏅 '+di;let l5='';if(i.languages.length)l5+='🇬🇧 '+i.languages.join(' • ');if(i.audioInfo){if(l5)l5+='  ';l5+='🔊 '+i.audioInfo}const lines=[l1,l2];if(l3)lines.push(l3);lines.push(l4);if(l5)lines.push(l5);return lines.join('\n')}
function filterAndArrange(streams,isSeries){const maxSize=isSeries?MAX_SERIES_SIZE_GB:MAX_MOVIE_SIZE_GB;const filtered=streams.filter(s=>{const t=s.title||s.name||'';if(EXCLUDE_KEYWORDS.some(k=>t.toLowerCase().includes(k)))return false;if(isProviderBlocked(t))return false;const gb=parseSizeGB(t);if(gb!==null&&gb>maxSize)return false;if(getSeeders(t)<MIN_SEEDERS)return false;return true});const groups={};for(const s of filtered){const q=extractQuality(s.title||s.name||'');(groups[q]||=[]).push(s)}const result=[];for(const[q,items]of Object.entries(groups)){const buckets={};for(const s of items){const src=s._source;(buckets[src]||=[]).push(s)}const picks=[];for(const[src,bucket]of Object.entries(buckets)){bucket.sort((a,b)=>{const pa=detectProvider(a.title||a.name||'');const pb=detectProvider(b.title||a.name||'');return providerSortKey(pa)-providerSortKey(pb)});picks.push(...bucket.slice(0,PER_SOURCE_LIMIT))}result.push(...picks)}result.sort((a,b)=>{return qualitySortKey(extractQuality(a.title||a.name||''))-qualitySortKey(extractQuality(b.title||a.name||''))});return result}

app.get('/manifest.json',(req,res)=>{res.json({id:'org.ghostream.plus',name:'Ghostream+ 🚀',description:'Stream Everything You Want\nMade With 🤍 By Van',version:'5.0.4',resources:['stream','subtitles'],types:['movie','series'],idPrefixes:['tt'],catalogs:[]})});

app.get('/subtitles/:type/:id.json',async(req,res)=>{try{const r=await axios.get(`${SUBTITLES_URL}/subtitles/${req.params.type}/${req.params.id}.json`,{timeout:15000});res.json(r.data)}catch(e){res.json({subtitles:[]})}});
app.get('/subtitles/:type/:id/:extra.json',async(req,res)=>{try{const r=await axios.get(`${SUBTITLES_URL}/subtitles/${req.params.type}/${req.params.id}/${req.params.extra}.json`,{timeout:15000});res.json(r.data)}catch(e){res.json({subtitles:[]})}});

app.get('/stream/:type/:id.json',async(req,res)=>{const{type,id}=req.params;const qs=req.url.split('?')[1]||'';const isSeries=type==='series';const sources=[{name:'torrentio',url:`https://torrentio.strem.fun/stream/${type}/${id}.json?${qs}&maxSize=4GB,1.5GB`},{name:'peerflix',url:`https://addon.peerflix.mov/language=en/stream/${type}/${id}.json?${qs}`}];const results=await Promise.allSettled(sources.map(src=>axios.get(src.url,{timeout:12000}).then(r=>{const streams=r.data.streams||[];return streams.map(s=>({...s,_source:src.name}))}).catch(()=>[])));let all=[];results.forEach(r=>{if(r.status==='fulfilled')all=all.concat(r.value)});const filtered=filterAndArrange(all,isSeries);const unified=filtered.map(s=>{const info=parseStreamInfo(s);let cleanName='';if(info.resolution){cleanName=info.resolution;if(info.ripType)cleanName+=' '+info.ripType}else if(info.ripType)cleanName=info.ripType;else cleanName=(s.title||s.name||'').split('\n')[0].trim();return{...s,name:cleanName,title:buildUnifiedTitle(s)}});res.json({streams:unified})});

app.listen(process.env.PORT||3000);